import { memo, useMemo } from 'react';
import { Canvas, Path, Skia } from '@shopify/react-native-skia';

import { ticketColors } from '@/constants/colors';
import { barcodeRowBleed, svgCoordinateDecimals } from '@/constants/drawing';

import type { BarcodeMatrix } from '@/api/types';

const DARK_MODULE = '1';
const fixed = (value: number) => value.toFixed(svgCoordinateDecimals);

interface BarcodeProps {
  matrix: BarcodeMatrix;
  width: number;
  height: number;
  color?: string;
}

/**
 * Draws the PDF417 module matrix generated by the API. Runs of dark modules in each row are
 * merged into rectangles and added to a single Skia path, so the whole barcode is one draw call.
 */
export const Barcode = memo(function Barcode({ matrix, width, height, color = ticketColors.ink }: BarcodeProps) {
  const path = useMemo(() => {
    const result = Skia.Path.Make();
    const moduleWidth = width / matrix.columns;
    const rowHeight = height / matrix.rows.length;
    matrix.rows.forEach((row, rowIndex) => {
      let runStart = -1;
      for (let column = 0; column <= row.length; column += 1) {
        const dark = row[column] === DARK_MODULE;
        if (dark && runStart < 0) runStart = column;
        if (!dark && runStart >= 0) {
          result.addRect({
            x: runStart * moduleWidth,
            y: rowIndex * rowHeight,
            width: (column - runStart) * moduleWidth,
            height: rowHeight + barcodeRowBleed,
          });
          runStart = -1;
        }
      }
    });
    return result;
  }, [height, matrix, width]);

  return (
    <Canvas
      style={{ width, height }}
      accessible
      accessibilityRole="image"
      accessibilityLabel={`Ticket barcode for ${matrix.payload.split('|').slice(1).join(', ')}`}
    >
      <Path path={path} color={color} />
    </Canvas>
  );
});

/** Same matrix as an SVG string, for the PDF ticket. */
export function barcodeSvg(matrix: BarcodeMatrix, width: number, height: number) {
  const moduleWidth = width / matrix.columns;
  const rowHeight = height / matrix.rows.length;
  const rects: string[] = [];
  matrix.rows.forEach((row, rowIndex) => {
    let runStart = -1;
    for (let column = 0; column <= row.length; column += 1) {
      const dark = row[column] === DARK_MODULE;
      if (dark && runStart < 0) runStart = column;
      if (!dark && runStart >= 0) {
        rects.push(
          `<rect x="${fixed(runStart * moduleWidth)}" y="${fixed(rowIndex * rowHeight)}" width="${fixed((column - runStart) * moduleWidth)}" height="${fixed(rowHeight + barcodeRowBleed)}"/>`,
        );
        runStart = -1;
      }
    }
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" fill="${ticketColors.ink}">${rects.join('')}</svg>`;
}
