export const iconStrokeWidths = {
  standard: 2.1,
  brand: 2.4,
} as const;

export const iconSizes = {
  xs: 13,
  sm: 16,
  md: 17,
  lg: 18,
  xl: 20,
  xxl: 24,
  train: 25,
  logo: 29,
} as const;

export const componentSizeKeys = {
  xs: 'xs',
  sm: 'sm',
  lg: 'lg',
  xl: 'xl',
} as const;

export const componentSizes = {
  headerHeight: '72px',
  navbarWidth: '286px',
  navbarBrandMinHeight: '68px',
  navScrollOffset: '86px',
  logoMark: '46px',
  loginLogoMark: '52px',
  searchWidth: '360px',
  searchInputMaxWidth: 520,
  searchViewportWidth: '42vw',
  stateMinHeight: '220px',
  stateIcon: '54px',
  tableMinWidth: 760,
  tableWideMinWidth: 920,
  tableJourneyMinWidth: 960,
  tableManifestMinWidth: 820,
  menuWidth: 240,
  avatar: 30,
  burger: 'sm',
  skeletonPanelHeight: 200,
  skeletonTallHeight: 360,
  skeletonTableHeight: 420,
  skeletonDetailHeight: 620,
  skeletonSmallTableHeight: 220,
  skeletonNetworkHeight: 240,
  skeletonRoutesHeight: 260,
  progressWidth: 92,
  chartHeight: 260,
  chartAxisWidth: 64,
  chartMaxBarWidth: 28,
  seatSize: '34px',
  seatSwatch: '18px',
  timelineDot: '12px',
  bookingFilterStatusWidth: '220px',
  bookingReferenceMinWidth: '160px',
  bookingsSearchMin: '240px',
  journeyFilterSearchMin: '220px',
  journeyFilterColumnMin: '150px',
  overviewAsideMin: '320px',
  journeyAsideWidth: '360px',
  authPanelWidth: '510px',
  authHeroColumnMin: '400px',
  authHeroMobileMinHeight: '360px',
  railArtHeight: '190px',
  trainWidth: '360px',
  trainViewportWidth: '62vw',
  trainHeight: '84px',
} as const;

export const fieldLimits = {
  stationCodeLength: 3,
  routeDistanceMin: 1,
  routeDistanceMax: 2000,
  carNumberMin: 1,
  carNumberMax: 99,
  compartmentMin: 1,
  compartmentMax: 12,
  repeatDaysMin: 1,
  repeatDaysMax: 30,
  delayMinutesMin: 0,
  delayMinutesMax: 1440,
} as const;
