/** Component dimensions. Interactive elements are at least `touchTarget` in each direction. */
export const sizes = {
  touchTarget: 44,
  iconButton: 44,
  avatar: 44,
  avatarLarge: 72,
  buttonHeight: 50,
  buttonHeightCompact: 44,
  buttonMinWidth: 150,
  buttonWideMinWidth: 200,
  inputHeight: 48,
  segmentHeight: 36,
  filterButtonHeight: 36,
  dateChipWidth: 56,
  dateChipHeight: 64,
  carPill: 46,
  stepperButton: 34,
  stepperValueMinWidth: 18,
  badgeDot: 9,
  badgeMinWidth: 44,
  emptyStateIcon: 56,
  optionIcon: 40,
  stationCodeWidth: 48,
  stationCodeHeight: 36,
  tripDateWidth: 58,
  tripDateHeight: 70,
  rowMinHeight: 60,
  cardRowMinHeight: 70,
  routeDot: 12,
  routeConnectorWidth: 14,
  routeDash: 2,
  routeFieldMinHeight: 52,
  radio: 24,
  legendSwatch: 16,
  legendHatchWidth: 22,
  legendHatchHeight: 2,
  pagerDot: 6,
  pagerDotActive: 18,
  ticketStackHeight: 22,
  tabItemMinHeight: 48,
  readableTextWidth: 300,
  skeletonCard: 250,
  skeletonRow: 64,
  skeletonListItem: 98,
  skeletonArchiveItem: 120,
  skeletonTicket: 520,
  skeletonSeatMap: 270,
  skeletonSummary: 56,
  skeletonLine: 18,
  skeletonConfirmation: 180,
  skeletonCityCard: 190,
  skeletonWidthShort: '60%',
  skeletonWidthMedium: '70%',
  authSceneHeight: 300,
  authSceneCompactHeight: 170,
  checkbox: 22,
  onboardingAnimation: 280,
} as const;

export const iconSizes = {
  xs: 14,
  sm: 16,
  md: 18,
  lg: 20,
  xl: 22,
  xxl: 24,
  tab: 22,
  hero: 26,
} as const;

export const hitSlop = { sm: 6, md: 10 } as const;
